"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  const router = useRouter();

const handleLogout = () => {
    alert("Logged out successfully");
    router.push("/"); 
  };


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <button onClick={handleLogout}
      style={{
       position:"absolute",
       backgroundColor:"red",
       width:"70px",
       top: "20px",
       right: "30px",
       padding:"10px",
       cursor:"pointer",
      }}>
      Logout
      </button>
        {children}
      </body>
    </html>
  );
}
